### ISSUE TITLE
GIthub ICON

### ISSUE THREAD

**Issue by RishabhDevbanshi** [RishabhDevbanshi/Windows-11-UI-Clone#1]
Just like VS Code and Chrome icon, add a GitHub icon which redirects to the repo of this project.

**Comment by alechash** [comment]
Good idea, I think you should have individual icons and working buttons on the dock too!

**Comment by RishabhDevbanshi** [comment]
> Good idea, I think you should have individual icons and working buttons on the dock too!

yeah , I am working on that.
